# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitshelf < Formula
  desc "Git changelists and shelves TUI, inspired by IntelliJ IDEA"
  homepage "https://github.com/ignaciotcrespo/gitshelf"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ignaciotcrespo/gitshelf/releases/download/v0.1.0/gitshelf_0.1.0_darwin_amd64.tar.gz"
      sha256 "beea83a8c76579e290472ce5783039ff0f8262126869abea00e71d0c09ebf077"

      define_method(:install) do
        bin.install "gitshelf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ignaciotcrespo/gitshelf/releases/download/v0.1.0/gitshelf_0.1.0_darwin_arm64.tar.gz"
      sha256 "57b4501f27afc8d7e0c8438803d8fa4be003c0a2b448c60cb2809c3c89f6898a"

      define_method(:install) do
        bin.install "gitshelf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ignaciotcrespo/gitshelf/releases/download/v0.1.0/gitshelf_0.1.0_linux_amd64.tar.gz"
      sha256 "8b38b227cf4b10ee2f3af44a0145ee3bf3857ba3c500bdd84c24846d4edf4a56"
      define_method(:install) do
        bin.install "gitshelf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ignaciotcrespo/gitshelf/releases/download/v0.1.0/gitshelf_0.1.0_linux_arm64.tar.gz"
      sha256 "883e0f2af46c12b04755acf1433d11390424175401e2e70939ae642ba00922f8"
      define_method(:install) do
        bin.install "gitshelf"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gitshelf --version")
  end
end
