# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitshelf < Formula
  desc "Git changelists and shelves TUI, inspired by IntelliJ IDEA"
  homepage "https://github.com/ignaciotcrespo/gitshelf"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ignaciotcrespo/gitshelf/releases/download/v0.6.0/gitshelf_0.6.0_darwin_amd64.tar.gz"
      sha256 "01a21583ae214c188546e40bf4d92ae93f1301e988b447e1f5b9b4e0c5638db3"

      define_method(:install) do
        bin.install "gitshelf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ignaciotcrespo/gitshelf/releases/download/v0.6.0/gitshelf_0.6.0_darwin_arm64.tar.gz"
      sha256 "af0efcc693b35a7d1e418176d018f034641a3a09f0aab4ee635a9ab495491b82"

      define_method(:install) do
        bin.install "gitshelf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ignaciotcrespo/gitshelf/releases/download/v0.6.0/gitshelf_0.6.0_linux_amd64.tar.gz"
      sha256 "328998d1bcf4c834ca395babd0f27600232e7a8f17ebe777a3911d131b5eb88b"
      define_method(:install) do
        bin.install "gitshelf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ignaciotcrespo/gitshelf/releases/download/v0.6.0/gitshelf_0.6.0_linux_arm64.tar.gz"
      sha256 "7f0d6c4d36360c1c15b4cb318726ca1acea4149526f5964f6530f312f240851c"
      define_method(:install) do
        bin.install "gitshelf"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gitshelf --version")
  end
end
