# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitshelf < Formula
  desc "Git changelists and shelves TUI, inspired by IntelliJ IDEA"
  homepage "https://github.com/ignaciotcrespo/gitshelf"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ignaciotcrespo/gitshelf/releases/download/v0.1.1/gitshelf_0.1.1_darwin_amd64.tar.gz"
      sha256 "3035c857453a5718f82b8db551756cedb61fe9b6a2c6e9ea40862811f5bd4d84"

      define_method(:install) do
        bin.install "gitshelf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ignaciotcrespo/gitshelf/releases/download/v0.1.1/gitshelf_0.1.1_darwin_arm64.tar.gz"
      sha256 "0186040441cc44c2272756eff21a7b25c864e451400aba6c86b652ad127a14da"

      define_method(:install) do
        bin.install "gitshelf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ignaciotcrespo/gitshelf/releases/download/v0.1.1/gitshelf_0.1.1_linux_amd64.tar.gz"
      sha256 "4c7249a1e2be97aa5e7eaa2cc7d1bf55fdfe82a926c8b19990eb1fdddcabdf4d"
      define_method(:install) do
        bin.install "gitshelf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ignaciotcrespo/gitshelf/releases/download/v0.1.1/gitshelf_0.1.1_linux_arm64.tar.gz"
      sha256 "e86bb98de25c3c548059ff87356dbb2aa11afc9e817b1f91ef96f3b16197e9b9"
      define_method(:install) do
        bin.install "gitshelf"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gitshelf --version")
  end
end
